# Generated by Django 3.1.2 on 2020-11-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_siteannouncement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteannouncement',
            name='link',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
