# Generated by Django 3.1.2 on 2020-11-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='chat',
            field=models.ManyToManyField(blank=True, null=True, related_name='messages', to='base.Message'),
        ),
    ]
