# Generated by Django 3.1.2 on 2020-11-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='chat',
            field=models.ManyToManyField(related_name='messages', to='base.Message'),
        ),
    ]
