# Generated by Django 3.1.2 on 2020-11-08 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField()),
                ('work_completed_in_time', models.BooleanField()),
                ('polite', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('behaviour', models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad'), ('Average', 'Average')], max_length=10)),
                ('rating', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_feed_customer', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_feed_worker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
