# Generated by Django 3.1.2 on 2020-11-09 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_workerfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerfeedback',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='workerfeedback',
            name='worker',
        ),
        migrations.AddField(
            model_name='workerfeedback',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.appointment'),
        ),
    ]
