# Generated by Django 3.1.2 on 2020-11-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20201109_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='work_name',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
