# Generated by Django 3.1.2 on 2020-11-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_appointment_work_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerfeedback',
            name='work_completed_in_time',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
    ]
