# Generated by Django 3.1.2 on 2020-11-08 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_skill', models.CharField(max_length=200)),
                ('secondary_skill', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_skill', models.CharField(blank=True, max_length=200, null=True)),
                ('primary_exp', models.IntegerField()),
                ('secondary_exp', models.IntegerField(blank=True, null=True)),
                ('additional_exp', models.IntegerField(blank=True, null=True)),
                ('primary_rate', models.IntegerField()),
                ('secondary_rate', models.IntegerField(blank=True, null=True)),
                ('additional_rate', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
