# Generated by Django 3.1.2 on 2020-11-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='additional_exist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='secondary_exist',
            field=models.BooleanField(default=True),
        ),
    ]
