# Generated by Django 3.1.2 on 2020-11-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20201108_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
