# Generated by Django 3.1.2 on 2020-11-08 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worker', '0003_skill_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behaviour', models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad'), ('Average', 'Average')], max_length=10)),
                ('support', models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad'), ('Average', 'Average')], max_length=10)),
                ('response', models.CharField(choices=[('Good', 'Good'), ('Bad', 'Bad'), ('Average', 'Average')], max_length=10)),
                ('rating', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_feed_customer', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_feed_worker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
