# Generated by Django 3.1.2 on 2020-11-09 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20201109_0812'),
        ('worker', '0004_customerfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerfeedback',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerfeedback',
            name='worker',
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.appointment'),
        ),
    ]
